### ISSUE TITLE
基础库下面的navigation包有问题

### ISSUE THREAD

**Issue by xuexixuexijpg** [FPhoenixCorneaE/JetpackMvvm#1]
![image](https://user-images.githubusercontent.com/57759182/166430378-0922b557-3839-406f-8723-3aec727c6a5d.png)

大佬，这个NavHostFragment下的两个属性是啥？这个重写的navigation导航github地址在哪啊？我在想，除了WMRouter和ARouter外，能不能利用Hilt和navigation组合实现单activity组件化的开发

**Comment by FPhoenixCorneaE** [comment]
> ![image](https://user-images.githubusercontent.com/57759182/166430378-0922b557-3839-406f-8723-3aec727c6a5d.png)
> 
> 大佬，这个NavHostFragment下的两个属性是啥？这个重写的navigation导航github地址在哪啊？我在想，除了WMRouter和ARouter外，能不能利用Hilt和navigation组合实现单activity组件化的开发

这俩属性是官方的navigation-fragment包下的属性，运行时没问题的，只是as的编译问题。原地址：https://github.com/hegaojian/JetpackMvvm。navigation本就可以实现单activity开发，hilt是依赖注入，你可根据你实际需要引入。
